version: '3'
services:
  database:
    image: postgres:11-alpine
    container_name: tbz-chat-database
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tbz_chat
  app:
    image: tarkin25/tbz-chat
    container_name: tbz-chat-app
    ports:
      - 80:80
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://database:5432/tbz_chat'
      SPRING_PROFILES_ACTIVE: 'postgres'
      INVITATION_BASE_URL: 'http://localhost/activate-account'
      REACT_APP_API_URL: 'http://localhost/api'
      MAIL_FROM: 'noreply.tbz.chat@gmail.com'
