version: '3'
services:
#  database:
#    image: postgres:11-alpine
#    container_name: tbz-chat-database
#    ports:
#      - 5431:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: tbz_chat
  app:
    image: tbz-chat
    container_name: tbz-chat-app
    ports:
      - 80:80
    environment:
      SPRING_PROFILES_ACTIVE: 'mariadb'
      INVITATION_BASE_URL: 'http://10.0.1.66/activate-account'
      REACT_APP_API_URL: 'http://10.0.1.66/api'
      MAIL_FROM: 'noreply.tbz.chat@gmail.com'
