spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
  profiles:
    active: dev
springdoc:
  swagger-ui:
    url: /api-docs.yaml
    operations-sorter: method
    tags-sorter: alpha