spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/tbz_chat
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    flyway:
        locations: classpath:db/migration/dev
    jpa:
        hibernate:
            ddl-auto: validate
mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: noreply.tbz.chat@gmail.com
    password: tbz-chat
    smtp:
        auth: true
        starttls:
            enable: true
    transport:
        protocol: smtp
    from: TBZ-Chat
invitation:
    base-url: http://localhost:3000/activate-account
    subject: Welcome to TBZ-Chat
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type: ERROR