spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/tbz_chat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration/postgres